"""Render captured API endpoints as a Markdown document."""

from __future__ import annotations

from collections import defaultdict
from typing import TYPE_CHECKING

if TYPE_CHECKING:
    from .api_interceptor import CapturedEndpoint


def render_api_map(endpoints: list[CapturedEndpoint]) -> str:
    """Group endpoints by prefix and render as Markdown."""
    groups: dict[str, list[CapturedEndpoint]] = defaultdict(list)

    for ep in endpoints:
        parts = ep.path.strip("/").split("/")
        # Group by first two path segments (e.g. "1.0/sports")
        prefix = "/".join(parts[:2]) if len(parts) >= 2 else parts[0]
        groups[prefix].append(ep)

    lines = ["# UG Office API Map", "", "Auto-generated by Playwright discovery crawler.", ""]

    for prefix in sorted(groups):
        lines.append(f"## /{prefix}")
        lines.append("")
        lines.append("| Method | Path | Status |")
        lines.append("|--------|------|--------|")
        for ep in sorted(groups[prefix], key=lambda e: (e.path, e.method)):
            status = str(ep.status) if ep.status else "—"
            lines.append(f"| `{ep.method}` | `{ep.path}` | {status} |")
        lines.append("")

    return "\n".join(lines)
